### ISSUE TITLE
[SUGGESTION] Notifications page button

### ISSUE THREAD

**Issue by srnyx** [devBoi76/modrinthify#5]
I'd love to have a button in the notification menu (or make the mod names of updates clickable) that leads to https://modrinth.com/notifications, would be a lot easier for managing notifications, since just clicking on the notification in Modrinthify won't clear the notification on Modrinth.

**Comment by srnyx** [comment]
Or, instead, a settings toggle that will make it so if you click on Modrinthify in the extensions list of the browser, it will open up https://modrinth.com/notifications (this is how [Notifier for GitHub](https://chrome.google.com/webstore/detail/notifier-for-github/lmjdlojahmbbcodnpecnjnmlddbkjhnn) works and it's absolutely fantastic).

**Comment by devBoi76** [comment]
Hi, sorry for the late response. Unfortunately due to Modrinth's current notification API it's impossible to clear the notification from outside the website, something like this could work pretty well though.

![image](https://github.com/devBoi76/modrinthify/assets/77896685/2e205d95-b08c-46de-b35b-5aa3f14a49f8)
![image](https://github.com/devBoi76/modrinthify/assets/77896685/cc10ed42-db94-4e0a-885d-f02df8acdcb1)

Also, as a kind of workaround you can "clear" old notifications using this cross button and they won't count towards the counter anymore 
![image](https://github.com/devBoi76/modrinthify/assets/77896685/e672bc72-0731-468c-93d6-d744946c9293)

**Comment by srnyx** [comment]
> a redirect like this could work pretty well though

What about my other suggestion? I think I'd like it a bit more; https://github.com/devBoi76/modrinthify/issues/5#issuecomment-1529918559

**Comment by devBoi76** [comment]
I'll try to add it as a toggle in the settings but I'm not sure how to do it yet, so I just added this simple version for now. I'll take a look at how notifier does it and try to add it 👍

**Comment by devBoi76** [comment]
Since notifications get actually cleared now (179e303ebe7ae81fa750388cd1e5f493fb66d8e2) I'll consider this issue fixed 👍
